apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" .}}-license
  labels:
    name: gw-license
  annotations:
    description: Template for Secrets for the Gateway license
type: Opaque
data:
  license: {{ .Values.gateway.license.value | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}