apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ template "gateway.fullname" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "gateway.fullname" . }}
  annotations:
    description: "The Gateway service"
spec:
  selector:
    app: {{ template "gateway.fullname" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
  ports:
{{- range .Values.service.ports }}
    - protocol: TCP
      port: {{ .external }}
      targetPort: {{ .internal }}
      name: {{ .name | quote }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
