dependencies:
  - name: influxdb
    version: ^1.0.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: grafana
    version: 1.21.2
    repository: https://kubernetes-charts.storage.googleapis.com/
