{{- if .Values.prodEnabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.prodClusterIssuerName }}
spec:
  acme:
    email: {{ .Values.acmeEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.prodClusterIssuerName }}
    dns01:
      providers:
        - name: {{ .Values.dnsProviderName}}
          clouddns:
            serviceAccountSecretRef:
              name: {{ .Values.clouddnsServiceAccountSecretRefName }}
              key: {{ .Values.clouddnsServiceAccountSecretRefKey }}
            project: {{ .Values.clouddnsProject }}
{{- end }}
